name: Daily Key

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Key
        run: |
          python3 - << 'EOF'
          import random
          import string

          key = "VB-" + ''.join(
              random.choices(
                  string.ascii_uppercase + string.digits,
                  k=10
              )
          )

          with open("key.txt", "w") as f:
              f.write(key)

          print(key)
          EOF

      - name: Commit
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add key.txt
          git commit -m "update key" || true
          git push
